### PR TITLE
Minor test updates

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
@blowekamp take a look

**Comment by dzenanz** [comment]
Tests fail due to memory allocation: the test driver cannot allocate both the test image and the baseline image in memory at the same time.

**Comment by dzenanz** [comment]
I think that `using` was added to avoid shadowing other variants of `SetRequestedRegion`.

And with restoration of `ITKKWStyleOvewrite.txt`, the KWStyle passes now locally, whereas it was failing with the exact message you quoted.

Which commit message does not conform to ITK's conventions?

**Comment by jhlegarreta** [comment]
> I think that `using` was added to avoid shadowing other variants of `SetRequestedRegion`.
> 
> And with restoration of `ITKKWStyleOvewrite.txt`, the KWStyle passes now locally, whereas it was failing with the exact message you quoted.

:+1: 

> Which commit message does not conform to ITK's conventions?

It's the PR, sorry.

Thanks for the effort !

**Comment by blowekamp** [comment]
Good to see you found the SERIAL ctest property.

👍

**Pull request merged**
