### PR TITLE
STYLE: Use trailing return type instead of typename + dependent type

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Review by tbirdso — APPROVED** [review]

**Comment by dzenanz** [comment]
It looks like a general CI update is needed here. Could you do that @tbirdso?

**Comment by tbirdso** [comment]
> It looks like a general CI update is needed here. Could you do that @tbirdso?

Yes, will take a look.

**Comment by dzenanz** [comment]
I just rebased it on top of your PR.

**Comment by dzenanz** [comment]
After merging this, we should tag `v1.0.1`. I don't think this remote has a Python package.

**Comment by tbirdso** [comment]
> I don't think this remote has a Python package.

@dzenanz To confirm, do you need a `pip`-installable Python package for your work or are you focused on the C++ library? We may need to set up the PyPI project if a Python package is required.

**Comment by tbirdso** [comment]
>  Just saying that once we tag, we should not expect Python package to be produced.

That's fine with me. Note that our current CI does in fact produce Python packages, though without attempting a local installation or providing Python tests it is unknown whether these are particularly useful.

https://github.com/KitwareMedical/ITKRLEImage/actions/runs/4823836618

If you think we'll never need Python packages for this repo, we could remove the Python packaging workflow to greatly speed up CI.

**Comment by dzenanz** [comment]
> remove the Python packaging workflow to greatly speed up CI

We should definitely do this! It would be good if you did this in a follow-up PR.

**Pull request merged**
